before:
  hooks:
    - go generate .

builds:
  - binary: webexec
    id: non-darwin
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - binary: webexec
    id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post: gon
universal_binaries:
  - replace: true

    # signs:
    # - signature: "${artifact}.dmg"
    # ids:
    # - darwin
    # cmd: gon
    # args:
    # - gon.hcl
    # artifacts: all
     
archives:
  - 
    replacements:
      darwin: darwin
      linux: linux
      freebsd: freebsd
      386: 386
      amd64: amd64
      arm: arm
      arm64: arm64
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - webexecd.sh

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
