before:
  hooks:
    - go generate .
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - 
    replacements:
      darwin: darwin
      linux: linux
      freebsd: freebsd
      386: 386
      amd64: amd64
      arm: arm
      arm64: arm64
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - webexecd.sh

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
