name: Release
on: 
  push:
    tags: ['v*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          if [[ ${GITHUB_REF#refs/tags/v} == refs* ]]; then
            echo ::set-output name=current_version::"Unreleased"
          else
            echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
          fi
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Save ChangeLog to file
        id: save_changes
        run: |
          export CF=$(mktemp)
          echo ::set-output name=changesfile::$CF
          echo "${{ steps.changelog_reader.outputs.changes }}" > $CF
        shell: bash
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args:
            release --rm-dist --release-notes ${{ steps.save_changes.outputs.changesfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
