name: Release
on:
  - push:
      tags: ['v*']
  - workflow_dispatch

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          if [[ ${GITHUB_REF#refs/tags/v} == refs* ]]; then
            echo ::set-output name=current_version::"Unreleased"
          else
            echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
          fi
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Save ChangeLog to file
        id: save_changes
        run: |
          export CF=$(mktemp)
          echo ::set-output name=changesfile::$CF
          echo "${{ steps.changelog_reader.outputs.changes }}" > $CF
        shell: bash
      - name: Create Footer File
        id: create_footer
        run: |
          export CF=$(mktemp)
          echo ::set-output name=footerfile::$CF
          echo "For complete history read the (changelog)[./CHANGELOG.md]" > $CF
        shell: bash
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERT }}
          P12_PASSWORD: ${{ secrets.P12_PASS }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASS }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-n@v2
        with:
          args:
            release --rm-dist --release-notes ${{ steps.save_changes.outputs.changesfile }} --release-footer ${{ steps.create_footer.outputs.footerfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_APPLICATION_IDENTITY: ${{ secrets.APPLE_APPLICATION_IDENTITY }}
          BUNDLE_ID: sh.webexec
