name: assets-sync
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  generate-authors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Create file
      run: .github/generate-authors.sh
    - uses: stefanweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update AUTHORS file"
        commit_user_email: "59523206+pionbot@users.noreply.github.com"
        commit_user_name: "Pion Bot"
