name: update-authors
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  generate-authors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Generate the AUTHORS file
      run: .github/generate-authors.sh

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update AUTHORS file"
        commit_user_email: "59523206+pionbot@users.noreply.github.com"
        commit_user_name: "Pion Bot"
